'use strict';

const SEVERITY_ICON = { critical: '🔴', high: '🟠', medium: '🟡', info: '✅' };
const SOURCE_LABELS = {
  heartbeat: '💓 Heartbeat', hooks: '🪝 Hooks', whatsapp: '📱 WhatsApp',
  subagents: '🤖 Subagents', skills: '🔧 Skills', memory: '🧠 Memory',
  primary_model: '⚙️ Primary Model', sessions: '💬 Sessions',
  workspace: '📁 Workspace', config: '📄 Config',
};

function generateMarkdownReport(analysis) {
  const { summary, findings, sessions, primaryModel, scannedAt } = analysis;
  const bleed = summary.estimatedMonthlyBleed;
  const lines = [];

  lines.push('# Clawculator Report');
  lines.push('> Your friendly penny pincher. · 100% offline · Zero AI · Pure deterministic logic');
  lines.push('');
  lines.push(`**Scanned:** ${new Date(scannedAt).toLocaleString()}`);
  if (primaryModel) lines.push(`**Primary model:** ${primaryModel}`);
  lines.push('');

  // Cost alert
  if (bleed > 0) {
    lines.push(`## ⚠️ Estimated Monthly Cost Exposure: $${bleed.toFixed(2)}/month`);
    lines.push('');
  } else {
    lines.push('## ✅ No significant cost bleed detected');
    lines.push('');
  }

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Severity | Count |');
  lines.push('|----------|-------|');
  lines.push(`| 🔴 Critical | ${summary.critical} |`);
  lines.push(`| 🟠 High | ${summary.high} |`);
  lines.push(`| 🟡 Medium | ${summary.medium} |`);
  lines.push(`| ✅ OK | ${summary.info} |`);
  lines.push(`| Sessions analyzed | ${summary.sessionsAnalyzed} |`);
  lines.push(`| Total tokens found | ${(summary.totalTokensFound || 0).toLocaleString()} |`);
  lines.push('');

  // Findings by severity
  lines.push('## Findings');
  lines.push('');

  for (const severity of ['critical', 'high', 'medium', 'info']) {
    const group = findings.filter(f => f.severity === severity);
    if (!group.length) continue;

    lines.push(`### ${SEVERITY_ICON[severity]} ${severity.toUpperCase()} (${group.length})`);
    lines.push('');

    for (const f of group) {
      lines.push(`#### ${SOURCE_LABELS[f.source] || f.source}`);
      lines.push('');
      lines.push(`**${f.message}**`);
      lines.push('');
      if (f.detail)          lines.push(`${f.detail}`);
      if (f.monthlyCost > 0) lines.push(`**Monthly cost:** $${f.monthlyCost.toFixed(2)}/month`);
      if (f.fix) {
        lines.push('');
        lines.push(`**Fix:** ${f.fix}`);
      }
      if (f.command) {
        lines.push('');
        lines.push('```bash');
        lines.push(f.command);
        lines.push('```');
      }
      lines.push('');
    }
  }

  // Session breakdown
  if (sessions?.length > 0) {
    lines.push('## Session Breakdown');
    lines.push('');
    lines.push('| Session | Model | Tokens | Cost |');
    lines.push('|---------|-------|--------|------|');

    [...sessions]
      .sort((a, b) => (b.inputTokens + b.outputTokens) - (a.inputTokens + a.outputTokens))
      .slice(0, 20)
      .forEach(s => {
        const tok  = (s.inputTokens + s.outputTokens).toLocaleString();
        const flag = s.isOrphaned ? ' ⚠️' : '';
        const keyDisplay = s.key.length > 12 ? s.key.slice(0, 8) + '…' : s.key;
        lines.push(`| \`${keyDisplay}${flag}\` | ${s.modelLabel || s.model} | ${tok} | $${s.cost.toFixed(6)} |`);
      });

    lines.push('');
  }

  // Quick wins
  const wins = findings.filter(f => f.fix && f.severity !== 'info');
  if (wins.length > 0) {
    lines.push('## Quick Wins');
    lines.push('');
    wins.slice(0, 5).forEach((f, i) => {
      lines.push(`${i + 1}. **${f.fix}**`);
      if (f.command) lines.push(`   \`${f.command}\``);
    });
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [Clawculator](https://github.com/echoudhry/clawculator) · Your friendly penny pincher.*');

  return lines.join('\n');
}

module.exports = { generateMarkdownReport };
